In [2]:
import numpy as np

In [12]:
a = np.arange(10)

In [14]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
b = np.arange(10)

In [18]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a * b

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [22]:
a + b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
np.arange(1,5,2)

array([1, 3])