# Introdction to numpy

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from 'C:\\Users\\DELL\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

## CREATING ARRAYS

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
array = [1,2,3,4,5,6,7]
nparray = np.array(array)

In [7]:
nparray[2]

3

In [8]:
nparray[2]=9
nparray

array([1, 2, 9, 4, 5, 6, 7])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(3,25)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24])

In [11]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

## Multi-dimentional arrays

In [12]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [15]:
n[0,1]

2

In [16]:
n[0,2]=20
n

array([[ 1,  2, 20],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [17]:
n[0]

array([ 1,  2, 20])

In [18]:
n[2] = n[2]*96
n

array([[  1,   2,  20],
       [  4,   5,   6],
       [672, 768, 864]])

In [19]:
n[:,2]

array([ 20,   6, 864])

## Randomly generated arrays

In [20]:
np.random.seed(5)
np.random.rand(3,4)

array([[0.22199317, 0.87073231, 0.20671916, 0.91861091],
       [0.48841119, 0.61174386, 0.76590786, 0.51841799],
       [0.2968005 , 0.18772123, 0.08074127, 0.7384403 ]])

In [21]:
np.random.randint(low=0,high=100,size=(5,2))

array([[44, 77],
       [75, 65],
       [47, 30],
       [84, 86],
       [18,  9]])

In [22]:
## Element wise operations

In [23]:
a1 = np.arange(5)
a1

array([0, 1, 2, 3, 4])

In [24]:
a1 * 3

array([ 0,  3,  6,  9, 12])

In [25]:
b1 = 10 + (a1 * 2) ** 2 /10

In [26]:
a1 + b1

array([10. , 11.4, 13.6, 16.6, 20.4])

## comparison operations

In [27]:
a1 > 3

array([False, False, False, False,  True])

In [28]:
a1 < b1

array([ True,  True,  True,  True,  True])

In [29]:
a1[a1 > 3]

array([4])

## Summarizing operations

In [30]:
a1.sum()

10

In [34]:
a1.mean(),a1.min(),a1.max()

(2.0, 0, 4)

In [33]:
a1.std()

1.4142135623730951